### PR TITLE
Add support for BubbleChart - Update index.js

### PR DESCRIPTION
**Pull request by orim181**
Add support for BubbleChart - based on https://github.com/ankane/chartkick/blob/master/vendor/assets/javascripts/chartkick.js

### CODE REVIEW

**Comment by orim181** [comment]
It looks straightforward but let me know otherwise.

**Comment by orim181** [comment]
For those that want to use the bubble chart, I published a fork on npm (sadly) until this PR is approved - https://www.npmjs.com/package/@orim181/vue-chartkick

**Comment by ankane** [comment]
Hey @orim181, thanks for the PR! Bubble charts are still experimental in Chartkick.js, which is why they're not available here.

**Comment by orim181** [comment]
Thanks @ankane. I could understand.

Do you think it helps to introduce it anyway under the same  “experimental” badge to help make your wrapper library more consistent with the underlying Chartkick.js library? 

Might be useful to those who’ve wanted to use it in its experimental form. Just a thought.

**Pull request closed without merging**
